stage:
  node-5:
    prepare:
      exec:
      - yum erase -y alinode-iojs && rm -f /opt/taobao/node
      - yum install -y alinode-iojs-5.* -b current
#      - PATH=/opt/taobao/node/bin:$PATH npm i -g tnpm@beta --registry=http://registry.npm.alibaba-inc.com
      - PATH=/opt/taobao/node/bin:$PATH tnpm i
    unit_test:
      exec:
      - "CI_BUILD_REF=$source_version CI_BUILD_REF_NAME=$scm_branch CI_BUILD_REPO=$scm_url \
          CI_BUILD_URL=http://cise.alibaba-inc.com/task/$task_id/build/$build_idx \
          PATH=/opt/taobao/node/bin:$PATH tnpm run ci"
  node-4:
    prepare:
      exec:
      - yum erase -y alinode-iojs && rm -f /opt/taobao/node
      - yum install -y alinode-iojs-4.* -b current
#      - PATH=/opt/taobao/node/bin:$PATH npm i -g tnpm@beta --registry=http://registry.npm.alibaba-inc.com
      - PATH=/opt/taobao/node/bin:$PATH tnpm i
    unit_test:
      exec:
      - "CI_BUILD_REF=$source_version CI_BUILD_REF_NAME=$scm_branch CI_BUILD_REPO=$scm_url \
          CI_BUILD_URL=http://cise.alibaba-inc.com/task/$task_id/build/$build_idx \
          PATH=/opt/taobao/node/bin:$PATH tnpm run ci"

pipeline:
#- node-5, node-4
- node-4